lortza/food_planner

- app/controllers/recipes_controller.rb
- app/helpers/ingredients_helper.rb
- app/helpers/recipes_helper.rb
- app/models/meal_plan.rb
- app/views/recipes/_form.html.erb
- app/views/recipes/show.html.erb
- db/migrate/20190425015705_add_reheat_instructions_to_recipes.rb
- db/schema.rb
- spec/factories/recipes.rb
- spec/helpers/recipes_helper_spec.rb
- spec/models/meal_plan_spec.rb
Closes #26 (add reheat instructions)
> 26 add reheat instructions

- app/views/devise/sessions/new.html.erb
- config/routes.rb
> Disable new account registration

- app/assets/stylesheets/shared.scss
- app/assets/stylesheets/shopping_lists.scss
- app/controllers/aisles_controller.rb
- app/helpers/numbers_helper.rb
- app/helpers/shopping_lists_helper.rb
- app/models/aisle.rb
- app/models/concerns/icon.rb
- app/models/shopping_list.rb
- app/models/shopping_list_item.rb
- app/views/aisles/_form.html.erb
- app/views/aisles/edit.html.erb
- app/views/aisles/index.html.erb
- app/views/aisles/new.html.erb
- app/views/shared/navbar/_signed_in.html.erb
- app/views/shopping_list_items/_form.html.erb
- app/views/shopping_lists/index.html.erb
- app/views/shopping_lists/show.html.erb
- config/routes.rb
- db/migrate/20190813235253_remove_number_from_aisles.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/aisles.rb
- spec/helpers/meal_plans_helper_spec.rb
- spec/helpers/numbers_helper_spec.rb
- spec/helpers/shopping_lists_helper_spec.rb
- spec/helpers/time_helper_spec.rb
- spec/models/aisle_spec.rb
- spec/models/shopping_list_item_spec.rb
> 41 aisle management

- .rubocop.yml
- .travis.yml
- app/channels/application_cable/channel.rb
- app/channels/application_cable/connection.rb
- app/controllers/recipes_controller.rb
- app/controllers/shopping_list_favorites_controller.rb
- app/controllers/shopping_list_items_controller.rb
- app/helpers/application_helper.rb
- app/helpers/numbers_helper.rb
- app/helpers/shopping_lists_helper.rb
- app/models/aisle.rb
- app/models/concerns/icon.rb
- app/models/meal_plan.rb
- app/models/recipe.rb
- app/models/shopping_list_item.rb
- spec/factories/recipes.rb
- spec/factories/shopping_list_items.rb
- spec/helpers/shopping_lists_helper_spec.rb
- spec/models/meal_plan_spec.rb
- spec/models/shopping_list_item_spec.rb
- spec/models/shopping_list_spec.rb
> 49 Fix :allthethings: !

- .dependabot/config.yml
> 48 Add dependabot

- Gemfile
- Gemfile.lock
closes #56 
closes #55 
closes #54 
closes #53 
closes #52
> Dependabot updates

- .travis.yml
- app/assets/stylesheets/meal_plans.scss
- app/assets/stylesheets/recipes.scss
- app/assets/stylesheets/shared.scss
- app/assets/stylesheets/shopping_lists.scss
- app/assets/stylesheets/variables.scss
- app/views/ingredients/_form_fields.html.erb
- app/views/meal_plans/show.html.erb
- app/views/recipes/index.html.erb
- app/views/shared/_delete_footer.html.erb
closes #59 
corrects all linter errors and configured CI to run the linter
> 59 scss lint

- .travis.yml
- app/controllers/bulk_list_item_managers_controller.rb
- app/helpers/ingredients_helper.rb
- app/models/aisle.rb
- app/models/bulk_list_item_manager.rb
- app/models/ingredient.rb
- app/models/meal_plan.rb
- app/models/shopping_list.rb
- app/models/shopping_list_item.rb
- app/views/meal_plans/show.html.erb
- app/views/shopping_list_items/_form.html.erb
- app/views/shopping_lists/show.html.erb
- config/routes.rb
- db/seeds.rb
- spec/factories/recipes.rb
- spec/models/aisle_spec.rb
- spec/models/bulk_list_item_manager_spec.rb
- spec/models/ingredient_spec.rb
- spec/models/meal_plan_spec.rb
- spec/models/recipe_spec.rb
- spec/models/shopping_list_item_spec.rb
- spec/models/shopping_list_spec.rb
- spec/models/user_spec.rb
> 65 add meal plan ingredients to shopping list

- lib/tasks/shopping_list_tasks.rake
Closes #67 
Adds rake task that copies items from the weekly list into the grocery shopping list.
> Add rake task for weekly items

- lib/tasks/shopping_list_tasks.rake
Adds a rake task that copies items from a monthly shopping list to the grocery list on the last day of the month.
> Add monthly items task

- app/controllers/shopping_lists_controller.rb
- app/models/shopping_list.rb
- app/views/shopping_lists/index.html.erb
- db/migrate/20191012171438_add_fields_to_shopping_lists.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/shopping_list_tasks.rake
- spec/models/shopping_list_spec.rb
> 104 protect shopping lists

- app/models/shopping_list.rb
- app/views/shopping_lists/show.html.erb
- db/migrate/20191013233803_remove_booleans_from_shopping_lists.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/shopping_list_tasks.rake
- spec/models/shopping_list_spec.rb
> Remove boolean fields

- app/models/shopping_list_item_recurrence.rb
- lib/tasks/shopping_list_tasks.rake
- spec/models/shopping_list_item_recurrence_spec.rb
Moves logic from inside the rake task to a separate class then condenses it into 1 reusable method.
> Refactor rake tasks

- app/controllers/recipes_controller.rb
- app/helpers/recipes_helper.rb
- app/helpers/shopping_lists_helper.rb
- app/models/concerns/icon.rb
- app/models/recipe.rb
- app/models/shopping_list_item_recurrence.rb
- app/views/meal_plans/show.html.erb
- app/views/recipes/_form.html.erb
- app/views/recipes/index.html.erb
- app/views/recipes/show.html.erb
- app/views/shared/_flashes.html.erb
- db/migrate/20191020190101_add_extra_work_note_to_recipes.rb
- db/schema.rb
- spec/models/recipe_spec.rb
- spec/models/shopping_list_item_builder_spec.rb
Closes #16 
Adds icon warning that this recipe will take extra time or work. Hovering over the icon will tell you what extra work is required. Unfortunately, i can't seem to screenshot the tooltip text, but it looks like `Heads up! socka lentils overnight`.
On the recipe show page
Meal plan show page
Recipes index
> 16 extra work flag

- app/controllers/experimental_recipes_controller.rb
- app/models/experimental_recipe.rb
- app/models/user.rb
- app/views/experimental_recipes/_form.html.erb
- app/views/experimental_recipes/edit.html.erb
- app/views/experimental_recipes/index.html.erb
- app/views/experimental_recipes/new.html.erb
- app/views/shared/navbar/_main.html.erb
- app/views/shared/navbar/_signed_in.html.erb
- config/routes.rb
- db/migrate/20191022020626_create_experimental_recipes.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/experimental_recipes.rb
- spec/models/experimental_recipe_spec.rb
- spec/models/user_spec.rb
YOLO just built this out as a way to organize recipes i find online but have not tried yet.
> Add link management for outside recipes to try

- app/models/meal_plan.rb
- app/views/shared/navbar/_main.html.erb
- app/views/shared/navbar/_signed_in.html.erb
- spec/models/meal_plan_spec.rb
Write cleaner logic for upcoming and future meal plans
> Refactor upcoming plan logic for simplicity

- app/models/shopping_list_item_recurrence.rb
- spec/models/shopping_list_item_recurrence_spec.rb
> Fix monthly reoccurrence bug & add biweekly

- app/assets/stylesheets/shared.scss
- app/controllers/meal_plans_controller.rb
- app/helpers/application_helper.rb
- app/views/meal_plans/index.html.erb
- config/routes.rb
> Copy meal plan

- app/views/shopping_lists/search.html.erb
> Closes #X
>
[screenshots here]
>
> Add link to search page

- app/controllers/recipes_controller.rb
- app/views/experimental_recipes/index.html.erb
- config/routes.rb
> Closes #120
> Makes it 1 step easier to convert an experimental recipe to a regular recipe
Adds link to index page. Also changes index items from weird list to tidy table with management links.
Autopopulates new recipe form with the info from the experimental recipe
> The controller method i made makes me feel mauve. BUT i did get it done. This is the sort to feature that feels like magic. It just does the behind the scenes stuff that a person imagines should happen. It is nice to knock this out after spending a lot of time feeling like i'm not good at figuring stuff out. silly me. So lessons learned: yeah i can figure stuff out. And it doesn't have to take forever either.
> 120 convert to recipe

- Gemfile
- app/controllers/experimental_recipes_controller.rb
- app/controllers/meal_plan_recipes_controller.rb
- app/controllers/meal_plans_controller.rb
- app/controllers/recipes_controller.rb
- app/helpers/environment_banner_helper.rb
- app/models/meal_plan.rb
- app/models/shopping_list_item.rb
- app/models/shopping_list_item_builder.rb
- script/run_ci_checks
- spec/db/seeds_helper_spec.rb
- spec/models/meal_plan_spec.rb
> Closes #169
> I don't like being surprised by linter errors in CI. I made a script that runs all 3 linters with the command `lint`.
> You have to `chmod` to be able to run a script. 
```
chmod -R 777 ./
```
This will make all files inside that directory read/writable
> 169 script for ci

- app/controllers/experimental_recipes_controller.rb
- app/models/concerns/searchable.rb
- app/models/experimental_recipe.rb
- app/models/recipe.rb
- app/views/experimental_recipes/index.html.erb
> There was no title tag on the Experimental Recipes page and this was unhelpful since I usually have multiple tabs open. I added this feature. Also, I chose to sort these recipes by title.
Before:
After:
> It was handy to have a `Sortable` module in place so that I could add another shared method to is. Now `Recipe`s and `ExperimetalRecipe`s have sorting methods.
> Add title tag and sort

- app/models/recipe.rb
- config/environments/production.rb
- spec/models/recipe_spec.rb
> Fix ingredient duping

- app/models/ingredient.rb
- db/seed_fixtures/ingredients.yml
- lib/tasks/tbs_change.rake
* Using `T` to indicate Tablespoons was not clear enough
* Switched all use of `T` to `TBS` in the data, seeds, and code
> Change T to TBS

- app/controllers/recipes_controller.rb
- app/views/recipes/_copy_for_user_form.html.erb
- app/views/recipes/_related_recipes.html.erb
- app/views/recipes/_share_with_user_form.html.erb
- app/views/recipes/show.html.erb
- app/views/shared/_add_to_shopping_list_dropdown.html.erb
- config/routes.rb
Closes #223
As an admin user, I sometimes want to copy a recipe i have into the account of another user. I've made this easier for myself by putting a form on the recipe show page. Now I can enter a known user's email address and copy a recipe to their account.
If a user is not found:
Success message:
* Sometimes you have to refactor your html.
* This feature felt relatively easy to implement. I am glad to have the skill to know how to do this.
> 223 share recipe with user email

- app/controllers/shopping_list_items_controller.rb
Related to #244 
Closes #249 
* Fixes bug where we could not add new items to the grocery list if it had never been on the list before. 
* I should add Sentry to this repo.
> Set status on create

- app/controllers/shopping_list_item_statuses_controller.rb
- app/controllers/shopping_list_items_controller.rb
- app/models/shopping_list_item.rb
- db/migrate/20200430000447_remove_purchased_from_shopping_list_items.rb
- db/schema.rb
> Remove purchased column

- app/assets/javascripts/shopping_lists.js
- app/assets/stylesheets/shared.scss
- app/assets/stylesheets/shopping_lists.scss
- app/controllers/shopping_lists_controller.rb
- app/helpers/shopping_lists_helper.rb
- app/models/shopping_list.rb
- app/views/aisles/_form.html.erb
- app/views/aisles/index.html.erb
- app/views/meal_plans/index.html.erb
- app/views/shopping_lists/_form.html.erb
- app/views/shopping_lists/index.html.erb
- app/views/shopping_lists/new.html.erb
- app/views/shopping_lists/show.html.erb
- spec/models/shopping_list_spec.rb
Closes #260
* the shopping list icons were kind of floating all over the place
* we had trouble with long list item names pushing control icons around
* we had some duplicate classes -- now moved to the `shared.scss`
* the "In Cart" icon could stand to be just the cart icon w/o words
* the shopping list index page's "new" form looked like a search form and was confusing. now that happens on its own page and has the same navigation behavior as other index pages.
* flexbox!
> 260 alignment flexbox

- app/controllers/meal_plans_controller.rb
- app/controllers/recipes_controller.rb
- app/views/meal_plans/index.html.erb
- app/views/recipes/index.html.erb
* will_paginate gem is not working correctly. I don't know what's up with it. Since I can't access my data with it, i'm commenting it out for now.
* i'm too tired to fix this right now.
> Comment out will_paginate

- app/controllers/meal_plans_controller.rb
- app/views/meal_plans/_form.html.erb
- app/views/meal_plans/show.html.erb
- db/migrate/20200829175932_add_notes_to_meal_plan.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/meal_plans.rb
* sometimes i do some thinking about substitutions or planning items to freeze. This information is not captured anywhere and stays in my head. It would be helpful for me, and mike if i had it in a useful place.
> Add notes to meal plan

- app/views/layouts/application.html.erb
* big ol' bug. The grocery list was not able to deactivate items on the back end. 
* I enjoyed using `git bisect` because, honestly, i was feeling lazy. I'm glad i did it because my thought path for the problem (pundit) was completely misplaced. Additionally, I had recently done a sweet refactor and i was feeling a little sad that it may have broken things. It didn't. All of my faith is restored... 😆 
* i should probably have capyb specs for this feature.
* i'm probably not going to build capyb specs for this feature :grimace: (perks of being a solo user for a personal project. i can wrastle with capyb at work.)
> Revert mistakenly removed line from head

- Gemfile
- Gemfile.lock
- app/helpers/styles_helper.rb
- bin/setup
- config/application.rb
- config/boot.rb
- config/cable.yml
- config/environment.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/application_controller_renderer.rb
- config/initializers/assets.rb
- config/initializers/backtrace_silencers.rb
- config/initializers/content_security_policy.rb
- config/initializers/cookies_serializer.rb
- config/initializers/filter_parameter_logging.rb
- config/initializers/inflections.rb
- config/initializers/mime_types.rb
- config/initializers/new_framework_defaults_6_0.rb
- config/initializers/wrap_parameters.rb
- config/locales/en.yml
- config/puma.rb
- config/spring.rb
- db/migrate/20201210014429_add_foreign_key_constraint_to_active_storage_attachments_for_blob_id.active_storage.rb
- spec/db/seeds_helper_spec.rb
- spec/models/meal_plan_spec.rb
Closes #360
Closes #354 
Closes #353 
Closes #352
Closes #351
* Also upgrades app to latest version of rails
> Gem upgrades

- Gemfile
- Gemfile.lock
- db/schema.rb
These should have gone out with #360
> Bullet and schema

- app/views/recipes/show.html.erb
* This PR adds checkboxes to the ingredients on the recipe show page. The purpose of the checkboxes is to help the food preparer (lol, me) keep track of what's been added.
> Replace bullets with checkboxes

- app/assets/stylesheets/utilities.scss
- app/views/shopping_list_item_statuses/activate.js.erb
- app/views/shopping_list_item_statuses/deactivate.js.erb
Closes #765
* shopping list items were being placed at the bottom of the active section and not under an aisle header
* this also solves a bug with the aisle-removing logic that was making the toggle fail. since the aisle dom element was null, the js just pooped out. hiding/showing the aisle instead of removing/adding it resolves the null problem
> Reinstate shopping list item in aisle

- app/views/aisles/edit.html.erb
- app/views/experimental_recipes/edit.html.erb
- app/views/layouts/application.html.erb
- app/views/meal_plans/edit.html.erb
- app/views/recipes/edit.html.erb
- app/views/scheduled_deliveries/_scheduled_deliveries.html.erb
- app/views/scheduled_deliveries/edit.html.erb
- app/views/shared/_delete_footer.html.erb
- app/views/shopping_list_items/edit.html.erb
- app/views/shopping_lists/edit.html.erb
- app/views/shopping_lists/show.html.erb
This PR does a small mixed bag of cleanup after recent work
* Implement danger zone delete for all models
* add margin to shopping list search
* remove font awesome cdn
> Implement danger zone delete for all models

- app/assets/stylesheets/recipes.scss
- app/assets/stylesheets/utilities.scss
- app/assets/stylesheets/variables.scss
- app/views/ingredients/_form_fields.html.erb
- app/views/recipes/_form.html.erb
- app/views/shopping_list_items/_form.html.erb
- spec/models/ingredient_spec.rb
Related to #790
Closes #790 
* editing a recipe on mobile is difficult because the form fields are squished and difficult to select/edit
* the qty field on both the recipe form and the list item form insist on half steps in some instances
| Before | After |
|-----|-----|
| <img width="394" alt="Screen Shot 2023-11-15 at 12 53 21 PM" src="https://github.com/lortza/food_planner/assets/8680712/c72e19f4-c9b6-4ac0-aa87-4e168cfcaaa1"> | <img width="393" alt="Screen Shot 2023-11-15 at 12 54 09 PM" src="https://github.com/lortza/food_planner/assets/8680712/a39ec3f2-b26e-4120-b188-076e055b5a07"> |
> Ingredients table styles

- Gemfile
- Gemfile.lock
- app/controllers/meal_plans_controller.rb
- app/models/recipe.rb
- app/views/meal_plans/_form.html.erb
- config/environments/development.rb
https://anne-richardson.sentry.io/issues/4717809202/?notification_uuid=cb313a9b-47aa-40c5-986a-045ce4828225&project=5223691&referrer=weekly_report
Also, I fixed the annoying icon issue and just made the recipe title the link
Before
After
> Resolve N+1s in meal plan form

- spec/requests/meal_plans_spec.rb
Relates to #1012
* removes specific order-by clause that was I put in place in #1012
> More deflake with Remove order by
