lortza/food_planner

app/assets/stylesheets/shared.scss
app/views/recipes/show.html.erb
spec/factories/recipes.rb

Closes #31 
This adds the second part of this ticket: the bootstrap tab styles. Now we can see all 3 sets of instructions in one tabbed space.

Add tabbed styles to recipe show

---

app/assets/stylesheets/shared.scss
app/assets/stylesheets/shopping_lists.scss
app/controllers/list_item_completions_controller.rb
app/models/concerns/icon.rb
app/models/shopping_list_item.rb
app/views/shared/navbar/_signed_in.html.erb
app/views/shopping_list_items/_form.html.erb
app/views/shopping_list_items/edit.html.erb
app/views/shopping_lists/edit.html.erb
app/views/shopping_lists/index.html.erb
app/views/shopping_lists/show.html.erb
config/routes.rb
db/seeds.rb

Closes #38
- Enables user to toggle between crossed-off state and un-crossed-off state by touch/clicking item name
- Also adjusts styles to fit more items on a screen.
Styles Before:
Styles After:
Toggle feature:

Toggle list items by crossing off/on

---

app/assets/stylesheets/shared.scss
app/controllers/completed_shopping_list_items_controller.rb
app/controllers/shopping_list_favorites_controller.rb
app/controllers/shopping_lists_controller.rb
app/helpers/shopping_lists_helper.rb
app/models/concerns/icon.rb
app/models/shopping_list.rb
app/models/shopping_list_item.rb
app/views/shopping_lists/index.html.erb
app/views/shopping_lists/show.html.erb
config/routes.rb
spec/models/shopping_list_item_spec.rb
spec/models/shopping_list_spec.rb

Closes #43 
Before there was no way of knowing which lists were favorites and no way of changing this state.
After, now we can see a yellow star next to the favorite list. There can only be 1 favorite at a time. On the index page, the lists are ordered with the favorite on top and then by alpha order.

Add star ★ toggle for favoriting shopping lists

---

.github/pull_request_template.md
app/controllers/shopping_list_item_builders_controller.rb
app/models/shopping_list_item_builder.rb
app/views/recipes/_related_meal_plans.html.erb
app/views/recipes/show.html.erb
spec/models/shopping_list_item_builder_spec.rb

> Closes #35
> A user can now add all ingredients of a recipe to the grocery list directly from the recipe show page. This feature was currently not available. 
> I've made quite a mess for myself. The adding of ingredients to a list has a lot of checking for nils. This feels like something is wrong, but I don't know what it is. It feels like overkill to have individual guaranteed objects for each of the 3 ingredient sources (meal plan, recipe, individual ingredient). Maybe I need a guaranteed ingredient?

35 add recipe items to grocery

---

app/controllers/meal_plan_recipes_controller.rb
app/models/meal_plan_recipe.rb
app/views/recipes/_related_meal_plans.html.erb
app/views/recipes/index.html.erb
config/routes.rb
spec/factories/meal_plan_recipes.rb
spec/models/meal_plan_recipe_spec.rb

> Closes #29
> The user now has the ability to add a recipe to the upcoming meal plan directly from the recipes `index` and `show` pages. This action also takes uniqueness into account. We don't let the user add the same recipe to a meal plan more than one time. After the transaction, the user is redirected back to the appropriate page instead of always going to the index, for example. 
A new button on the recipes#index to add to the upcoming meal plan
A new link on the recipe show page to add to the upcoming meal plan
A successful addition to a meal plan shows a flash message on the page. 
If the user attempts to add the same recipe twice, they'll see this error. 
I was set back by confusing foreign key error messages when I wrote tests for the uniqueness validations. The hard-learned …

29 add recipe to meal plan from index and show pages

---

app/controllers/shopping_list_item_builders_controller.rb
app/helpers/meal_plans_helper.rb
app/helpers/recipes_helper.rb
app/models/ingredient.rb
app/models/shopping_list_item_builder.rb
app/views/meal_plans/show.html.erb
app/views/recipes/show.html.erb
spec/models/shopping_list_item_builder_spec.rb

> Closes #141 
> Simplifies shopping list builder code to just have to know the shopping list id and ingredient ids
- Rails doesn't really like passing objects or relationships from the view to the controller, and prefers `ids`. 
- As of rails 5, the syntax for redirecting back is `redirect_back`. More about that [here](https://medium.com/@hsdeekshith/redirect-to-back-is-deprecated-in-rails-5-what-to-use-instead-7ac8e970cd39).
- This change simplifies the tests a lot, and moving the logic to one `let` avoids having to change code in all the places when the logic changes. For example, I went back and forth between passing ids and objects, and before refactoring the tests, I had to change lots of places.
- There's some more refactoring I want to do, particularly making …

Refactor shopping list item builder to need only shopping list id and ingredient ids

---

app/controllers/aisles_controller.rb
app/models/aisle.rb
app/models/concerns/searchable.rb
app/models/shopping_list_item.rb
app/views/aisles/_form.html.erb
app/views/aisles/index.html.erb
app/views/shopping_list_items/_form.html.erb
app/views/shopping_lists/show.html.erb
db/migrate/20191125193320_add_order_number_to_aisles.rb
db/schema.rb
db/seeds.rb
spec/factories/aisles.rb
spec/models/aisle_spec.rb
spec/models/shopping_list_item_spec.rb

> The ordering of aisles got a little out of hand. We have a mix of strings and numbers and they don't sort well together. Ordering them by name didn't work and ordering them by anything else made the system brittle. When I added a new aisle, everything was thrown off in the dropdowns. Now we're ordering by a dedicated `order_number` field and tranquility has been restored to the world of aisles. 
> * "unassigned" is now restored as the default aisle on the form
> * the shopping_lists#show is now in order
> This took a lot of thinking about how I wanted to approach this problem. I think in the future, I'd like to be able to drag/drop aisles into order.

Order aisles

---

app/assets/javascripts/shopping_lists.js
app/controllers/recipes_controller.rb
app/controllers/shopping_lists_controller.rb
app/models/concerns/searchable.rb
app/models/recipe.rb
app/models/shopping_list.rb
app/models/shopping_list_item.rb
app/views/shared/_search_form.html.erb
app/views/shopping_lists/index.html.erb
app/views/shopping_lists/search.html.erb
app/views/shopping_lists/show.html.erb
config/routes.rb

> Closes #80
> Now a user can search for an item before adding a new one to the list. This keeps our list cleaner and easier to manage. This is still just a baby step in creating a seamless experience. I'm rolling it to production because it is better than what we currently have.
Finding an existing item
Searching for and then creating a new item
1. UX is hard. I had to really think through what i wanted the exact steps to be. Even so, i don't love the outcome. 
2. Just like ruby, javascript doesn't like calling functions on null objects. So if you're reusing JS on several pages that may not have the every object the JS is looking for, you need to do a presence check before trying to run code that calls a function on a nil var.

80 improve grocery list adding

---

app/controllers/shopping_list_items_controller.rb
app/views/shopping_list_items/new.html.erb
app/views/shopping_lists/search.html.erb
app/views/shopping_lists/show.html.erb

> When creating a new shopping list item, it was a pain to have typed a thing to search, not find it, and then have to type it again in order to create a new item. This stores that searched term and populates it in the form field. 
> Params are a lovely thing to pass around.

Autopopulate search term in new item

---

app/assets/stylesheets/shared.scss
app/helpers/environment_banner_helper.rb
app/views/layouts/_environment_banner.html.erb
app/views/layouts/application.html.erb

> Closes #126
> Too many times, I have found myself refreshing the production page and wondering why my changes weren't showing up. This is frustrating and a silly waste of time. Now it is clear when I am looking at a page in my development environment. 
> You can grab nifty git info from the command line using `Rails.env` and `ENV.fetch()`.

126 Add banner to top of site when env == development

---

app/helpers/meal_plans_helper.rb
spec/helpers/meal_plans_helper_spec.rb

> I found myself wanting to get to the recipe easily from this page but there were no links to do so. Now each recipe title is linked to the recipe show page. 
Before: No links
After: Totes links
> It sure was handy having the [`danebook` project](https://github.com/lortza/project_danebook/blob/master/app/helpers/likes_helper.rb#L3-L7) as reference when i needed to map over a bunch of items _and_ return a link.
```ruby
def list_likes(likes)
raw(likes.limit(3).map do |like|
link_to like.user.name, user_timeline_path(like.user)
end.join(", "))
end
```
```ruby
def display_recipes(meal_plan)
raw(meal_plan.recipes.map do |recipe|
link_to recipe.title, recipe
end.join(', '))
end
```
I should probably write a blog post about this so that I can find it again more easily and also help others to …

Convert recipe titles to links

---

app/views/recipes/_add_to_meal_plan_dropdown.html.erb
app/views/recipes/_related_meal_plans.html.erb
app/views/recipes/index.html.erb

> Related to #143
> Previously there was a link on the recipe show page to add a recipe to the next upcoming plan. This was the first step in making it easier to add recipes to meal plans. This PR is the next step: being able to add a recipe to  _any_ upcoming plan. 
Before: link to add to upcoming meal plan
After: replaced with dropdown to add recipe to any future meal plan
> Having a well-designed partial that I could reuse make this task unbelievably easy. Unfortunately, i had to pull the "should i display this dropdown?" logic out of the partial and put it in 2 places. I wonder if there is a tidier way to do this.

Replace link with dropdown

---

.rubocop.yml
Gemfile
app/models/recipe.rb
spec/models/recipe_spec.rb

> Related to #206 
> I wanted to figure out a way to safely dupe my recipes for my mom to see. Instead of going rogue and doing this on the console, i wrote a method  that i'll be able to use to do this. I took this approach because duping incorrectly would cause me sadness in my production data. I wrote tests to make sure the method does what i expect it to do (and nothing more).
> `dup`, `clone`, and `deep_dup` all behave a little differently. There are gems to handle this, but since i'm not doing this extensively, i just wrote a little method to handle it. 
> Low. This is an additive change that is not being called anywhere yet.

Add duping method

---

.github/pull_request_template.md
app/controllers/shopping_list_item_builders_controller.rb
app/views/meal_plans/show.html.erb
app/views/recipes/show.html.erb
app/views/shared/_add_to_shopping_list_dropdown.html.erb
app/views/shopping_lists/index.html.erb
spec/helpers/recipes_helper_spec.rb

Closes #70
> Allows me to choose which shopping list I want to add ingredients to. Defaults to my "favorite" list, which is my Grocery list.
Before
After
Before
After
The rails `form_tag` helper method called `hidden_field_tag` does not handle arrays of `id`s well. It converts them to a space-separated string. I posted [my solution on stackoverflow](https://stackoverflow.com/a/60468228/5009528). In a nutshell though, I fix the array in the controller:
The controller:
```ruby
ids_i_need = permitted_params[:ingredient_ids].split(' ').map(&:to_i)
def permitted_params
params.permit(:shopping_list_id, :ingredient_ids)
end
```
The view:
```html
<%= form_tag(shopping_list_item_builders_path, method: 'post', id: 'add-to-list-form' ) do %>
<%= hidden_field_tag :ingredient_ids, ingredient_ids %> …
```

70 choose list for recipe and meal plan ingredients

---

app/controllers/recipes_controller.rb
app/models/recipe.rb
spec/models/recipe_spec.rb

Closes #218
Sorting recipes alphabetically has not been particularly useful since I just search for the recipes i am looking for. I'm trying an experiment where I put recipes that I have not made in a while at the top of the list. This way I don't have to do as much digging while doing meal planning. I don't know if I will end up liking this feature. 🤷‍♀ We'll see!
My specs didn't pass until i did all of the proper "includes" like: 
```ruby
ordered_recipes = Recipe.includes(:meal_plans, :meal_plan_recipes).by_last_prepared
```

Order recipes by last_prepared

---

app/controllers/recipes_controller.rb
app/views/recipes/show.html.erb

Relates to #205
* Users don't have to have an account to see recipe show page
A signed-in user sees this:
An unauthenticated user sees this:
* It is very easy to knock out this single authorization feature. I chose to do just this one thing right now because this is the most urgent feature I need. I will continue to work through the complete `pundit` setup for #205 in a subsequent PR.

Allow non-users to view recipe show page

---

app/assets/stylesheets/recipes.scss
app/helpers/ingredients_helper.rb
app/views/recipes/_related_recipes.html.erb
app/views/recipes/show.html.erb
app/views/shared/_add_to_shopping_list_dropdown.html.erb
spec/helpers/ingredients_helper_spec.rb

* moves ingredient preparation style next to ingredient
* allows image to be full width of column
* hides "related recipes" section on mobile
* expands stats, meal plans, and sidebar to 100% on mobile
* fixes width problem on "add to list" form
* Needs change over time. It's good to try things out and then adjust them as needs change.
* Bootstrap has classes that hide things for mobile.
* Cherry picking little mini features that i spin off while in the middle of another feature is satisfying. This way i can still move forward while working on something bigger and more complicated.

Make recipe show more mobile-friendly

---

app/controllers/recipes_controller.rb
app/services/user_data_setup.rb
app/views/recipes/_form.html.erb
app/views/recipes/show.html.erb
db/seed_fixtures/experimental_recipes.yml

I no longer have a pepperplate.com account. Displaying links to these old recipes is worthless and confusing. I've removed the form field and links on the show page.

Remove links to pepperplate

---

.github/pull_request_template.md
app/models/shopping_list_item_builder.rb
db/migrate/20200425181637_add_status_to_shopping_list_items.rb
db/migrate/20200425181852_populate_status_data.rb
db/migrate/20200425182449_add_null_constraint_to_list_item_status.rb
db/schema.rb
db/seeds.rb
spec/factories/shopping_list_items.rb

Related to #244
* This PR is the first in a series PR to complete this feature. This work adds a new column, populates it with data, and follows up by adding a null constraint on the new column with data in it.
* Add new due diligence checks to PR template 
* I broke this work into 3 migrations so that if one of them failed, it would be easier to pinpoint and roll back. 
* We're not using official data migrations in this app, so I made the choice to use a single migration to manage the data portion of this work.
* I broke my seeds and factories because i had not updated them with this new column (and its glorious not null constraint). Thankfully CI caught it. To help me catch those mistakes in the future, I've added those check to the PR template. It would be nice to automate that check.

Add status column to shopping list items

---

app/assets/javascripts/shopping_lists.js
app/controllers/shopping_list_item_builders_controller.rb
app/controllers/shopping_list_item_statuses_controller.rb
app/controllers/shopping_list_items_controller.rb
app/models/shopping_list_item.rb
app/models/shopping_list_item_builder.rb
app/models/shopping_list_item_recurrence.rb
lib/tasks/shopping_list_tasks.rake
spec/factories/shopping_list_items.rb
spec/models/shopping_list_item_builder_spec.rb
spec/models/shopping_list_item_recurrence_spec.rb
spec/models/shopping_list_item_spec.rb

Related to #244
This PR does some cleanup work to set us up for the next phase of removing the `purchased` column. I had originally intended to work on some javascript toggle functionality, but i'm finding that i need to spend more time using the app to see if i like how it works before investing more time into this particular approach. 
* naming is hard!
* refactoring is fun!
* javascript is always uncomfortable for me

244 Refactor, refine, debug in_cart shopping_list_item

---

app/controllers/scheduled_deliveries_controller.rb
app/helpers/scheduled_deliveries_helper.rb
app/models/scheduled_delivery.rb
app/models/shopping_list.rb
app/views/scheduled_deliveries/_form.html.erb
app/views/scheduled_deliveries/_scheduled_deliveries.html.erb
app/views/scheduled_deliveries/edit.html.erb
app/views/scheduled_deliveries/new.html.erb
app/views/shopping_lists/show.html.erb
config/initializers/date_formats.rb
config/routes.rb
db/migrate/20200517165415_create_scheduled_deliveries.rb
db/schema.rb
spec/factories/scheduled_deliveries.rb
spec/helpers/scheduled_deliveries_helper_spec.rb
spec/models/scheduled_delivery_spec.rb
spec/models/shopping_list_spec.rb

* Now that we're scheduling deliveries more regularly, it's nice to have a reminder of when the next delivery is happening
* we can add upcoming deliveries to a shopping list
* only "future" deliveries are displayed  -- and disappear after they expire
* UX is hard

Add delivery dates

---

app/controllers/meal_plans_controller.rb
app/controllers/recipes_controller.rb
app/views/meal_plans/index.html.erb
app/views/recipes/index.html.erb

Closes #297
* gem `will_paginate` querying is suffering from a bit of `DISTINCT` sql confusion because of joining or `recipes` and `meal_plan_recipes`.

Reinstate pagination

---

app/controllers/meal_plans_controller.rb
app/models/meal_plan.rb
spec/models/meal_plan_spec.rb
spec/rails_helper.rb

Sometimes i like to build out several weeks of meal plans at once. This work does the math for me so i don't have to reference a calendar to know when the next Sunday is. It takes the date from the latest `meal_plan.start_date`, regardless of what day of the week it is, and auto-populates the form with the next Sunday following that date.
http://yay-me.herokuapp.com/posts/762
A good use-case for using `expect(X).to_receive(Y)` in testing:
When you have a condition in a method, instead of writing tests for a whole logic tree that may already fall under the jurisdiction of another test, it makes sense to just ask if that method was called.
The method
```ruby
class Kitten
def self.something_cute_with_kittens(user)
if any?
else
already_tested_method
end
end
def self.already_tested_method
end …
```

Suggest next plan date

---

Gemfile
app/controllers/meal_plan_recipes_controller.rb
app/controllers/meal_plans_controller.rb
app/helpers/application_helper.rb
app/models/meal_plan.rb
app/models/recipe.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/edit.html.erb
app/views/meal_plans/index.html.erb
app/views/meal_plans/show.html.erb
app/views/recipes/_add_to_meal_plan_dropdown.html.erb
app/views/recipes/_related_meal_plans.html.erb
db/migrate/20210128014008_change_meal_plan_start_date_column_name.rb
db/schema.rb
db/seeds.rb
db/seeds_original.rb
spec/factories/meal_plans.rb
spec/features/recipes_show_page_authorization.rb
spec/helpers/recipes_helper_spec.rb
spec/models/meal_plan_spec.rb
spec/models/recipe_spec.rb
spec/requests/meal_plans_spec.rb

Related to #372
* `start_date` was kind of a weird name. `prepared_on` seems to make more sense given how we use it. 
* I had let the scope of #372 spiral a little bit. I broke this piece out of that PR so the diff is single-purpose and will make building out the new functionality #372 easier to read in the diff.

Rename meal_plan.start_date to prepared_on

---

app/views/recipes/show.html.erb

Reduces spaces around checkbox line items and adds some bottom margin to the section:

Adjust spacing around ingredient checkboxes

---

Gemfile.lock

Reverts lortza/food_planner#494
This failed to deploy to heroku and i don't know why yet, so i'm just going to get it out of the way.

Revert "Bump pundit from 2.1.1 to 2.2.0"

---

.github/pull_request_template.md
.rubocop.yml
app/controllers/recipes_controller.rb
app/models/recipe.rb
app/services/cronometer_parser.rb
app/views/recipes/_form.html.erb
app/views/recipes/_nutritional_information.html.erb
app/views/recipes/show.html.erb
db/migrate/20221018163452_add_nutrition_data_iframe_to_recipes.rb
db/schema.rb
db/seed_fixtures/recipes.yml
spec/factories/recipes.rb
spec/services/cronometer_parser_spec.rb

I've been meaning to do a ton of work to get nutrition information into this app and I just haven't done it [years keeps on passing by]. I have been using the very thorough cronometer.com site to help me understand recipe ingredient breakdown. As I've been trying to find another solution to help me with meal planning, so far, everything else is disappointing. I really prefer my own app. 🤷 To help with nutritional data in the meantime, I've added a way to display the data from cronometer on the recipe show page. This seems like the easiest lift right now.
This approach has its limitations since it requires:
* all users (ahem, me) to have a cronometer account
* the user to create a custom recipe in cronometer and then copy the iframe src into the recipe in this app
I've added the …

Add option to display nutritional data panel from cronometer.com

---

app/helpers/ingredients_helper.rb
app/models/ingredient.rb
app/views/meal_plans/show.html.erb
spec/factories/ingredients.rb
spec/helpers/ingredients_helper_spec.rb

I thought it was time to make the ingredient display look smarter with pluralization. The tricky part is that sometimes we pluralize the measurement unit, like "3 **cups** water" but other times we pluralize the food name, like "3 medium **carrots**".  This PR handles that logic for the recipe show page and the meal plan show page.
The recipe show page does not pluralize any part of the ingredient listing.
The meal plan show page does not pluralize any part of the ingredient listing.
The recipe show page pluralizes ingredients when there is a descriptive measurement unit, like "large" or "whole" and pluralizes the measurement unit for normal units like "cup" or "tablespoon".
The meal plan show page pluralizes in the same pattern as the recipe show page. Also, the link to the recipe is now …

Add pluralization to ingredient displays

---

Procfile

Adds Procfile for production as per Heroku's recommendations
https://devcenter.heroku.com/articles/procfile
https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server
* WEBrick is the default server unless other Rails configurations have determined otherwise.
* It is better to be explicit. 
* Puma is the recommend server.

Add Procfile for production

---

app/views/shopping_lists/show.html.erb

The adding of items to the grocery list is not seamless. It takes two steps every time. It would be nice to fix this. This PR does not fix it. However, it does make selecting an existing item a little bit easier by preloading them into a `<datalist>` for the input field. Ideally, you'd just touch the item you want to add and be done with it, but we're not there yet. This is still an improvement because it lessens the keystrokes needed on mobile.

Add existing items to supplement browser autofill

---

app/controllers/meal_plan_recipes_controller.rb
app/controllers/scheduled_deliveries_controller.rb
app/helpers/application_helper.rb
app/views/scheduled_deliveries/edit.html.erb

Got some sentry errrors tonight:
https://anne-richardson.sentry.io/issues/4071035180/?referrer=alert_email&alert_type=email&alert_timestamp=1680911609420&alert_rule_id=1078349&environment=production&ref_fallback=ga
sentry error:
```
ArgumentError: wrong number of arguments (given 1, expected 0)
app/helpers/application_helper.rb:31:in `to_s'
link_to "Meal Plan: #{upcoming.prepared_on.to_s(:short)}", meal_plan_path(upcoming), class: 'nav-link' if upcoming
app/helpers/application_helper.rb:31:in `display_link_to_plan'
link_to "Meal Plan: #{upcoming.prepared_on.to_s(:short)}", meal_plan_path(upcoming), class: 'nav-link' if upcoming
app/views/shared/navbar/_signed_in.html.erb:15:
<%= display_link_to_plan %>
app/views/shared/navbar/_main.html.erb:9:
<%= render 'shared/navbar/signed_in' if …
```

Hot fix: Convert to_s to to_fs

---

app/helpers/recipes_helper.rb
app/views/meal_plans/show.html.erb
app/views/recipes/show.html.erb

I found that any notes I was writing in the Meal Plan notes weren't very visible. They seemed like an afterthought on the page when they're actually pretty important to pay attention to on food prep day. Same goes for the extra work note on the recipe show page. This PR makes both of those pieces of information easier to notice by breaking them out of the bulleted lists they were in and giving them their own sections.
| Page | Before | After |
|----|----|---|
| Recipe show page | <img width="722" alt="Screen Shot 2023-09-18 at 6 45 00 PM" src="https://github.com/lortza/food_planner/assets/8680712/db48c586-0c65-4082-9042-c4e755d10912"> | <img width="753" alt="Screen Shot 2023-09-18 at 6 41 31 PM" src="https://github.com/lortza/food_planner/assets/8680712/96ea9f57-1dde-4276-b2e4-aa285d9be53d …

Make extra work note more visible on show pages

---

app/views/recipes/_form.html.erb
app/views/recipes/show.html.erb

Closes #744 
* The notes section hiding on mobile
* moved the related meal plans off to the right sidebar since it is not crucial info
* "heads up" note is now more visible
|  Before | After | 
|-----|-----|
| under related meal plans | right after heads up note |
| heads up note is small | heads up note is own alert box |
| <img width="448" alt="Screen Shot 2023-10-02 at 7 02 18 PM" src="https://github.com/lortza/food_planner/assets/8680712/d0083f4a-bf74-48db-8b54-cc8e9b6bc1be"> | <img width="448" alt="Screen Shot 2023-10-02 at 7 02 36 PM" src="https://github.com/lortza/food_planner/assets/8680712/1ff5aacc-39e1-4be7-b1e8-02c158888d61"> |
After: full screen size

Move notes up

---

app/assets/stylesheets/shopping_lists.scss
app/controllers/shopping_list_item_statuses_controller.rb
app/views/shopping_list_item_statuses/deactivate.js.erb
app/views/shopping_lists/show.html.erb

Closes #762
When crossing items off of a shopping list, when you cross off the last item of an aisle, the aisle header stays on the list. This is weird looking. This PR removes the aisle when the last item is crossed off. 
This PR does not do the work of reinstating the aisle upon reactivating an item (clicking an item that is crossed off to put ut back on the list).
I also made the aisle headers a little bigger looking for better visibility on mobile while shopping:
| before | after |
|----|----|
| <img width="379" alt="Screen Shot 2023-10-18 at 8 19 09 AM" src="https://github.com/lortza/food_planner/assets/8680712/6164db7a-98fc-4f47-a28c-8b330f86f590"> | <img width="382" alt="Screen Shot 2023-10-18 at 8 17 42 AM" src="https://github.com/lortza/food_planner/assets/8680712/720088d7-8d42-44 …

Remove aisle when empty

---

app/views/shopping_list_item_statuses/activate.js.erb

The sweet shopping list item reinstatement does not work on a freshly loaded page. If the aisle exists on that page load, you _can_ cross off an item and then put it back. BUT if you refresh the page and _then_ want to reinstate an item, it doesn't know where to go. This PR fixes that bug by appending the item to the active items section in the case that it can't find its aisle. 
I should probably have some capybara tests... 😆

Handle null aisle when reinstating shopping list items

---

app/views/shopping_list_item_statuses/deactivate.js.erb

On a fresh page load, a deactivated item does not have a hidden aisle in the DOM. When reactivating an item that does not have an aisle and then deactivating it again, the JS fails because it assumes the presence of the aisle before trying to hide it. This results in the newly deactivated item not being inserted in the inactive section. This PR no longer assumes the aisle's presence, which allows the JS to continue and the item to be inserted in the inactive section.

Fix shopping list item deactivate

---

app/components/material_icon.rb
app/helpers/recipes_helper.rb
app/views/shopping_list_item_statuses/activate_from_search.js.erb
app/views/shopping_list_items/_shopping_list_item.erb
spec/helpers/recipes_helper_spec.rb

This PR does a little more tweaking to some recent changes. 
* Update location of confirmation badge after item is added to shopping list
* Replace "archived" status indicator with badge
| Before | After |
|-----|----|
| <img width="741" alt="Screen Shot 2023-10-21 at 10 53 28 AM" src="https://github.com/lortza/food_planner/assets/8680712/293cc742-b977-44f1-a3d8-e033fa626d87"> | <img width="745" alt="Screen Shot 2023-10-21 at 10 51 07 AM" src="https://github.com/lortza/food_planner/assets/8680712/79745278-56a3-4dce-bd31-74f190083682"> |
| <img width="722" alt="Screen Shot 2023-10-21 at 11 22 58 AM" src="https://github.com/lortza/food_planner/assets/8680712/56f2bd1d-b7ef-430f-9794-f3597b54da76"> | <img width="719" alt="Screen Shot 2023-10-21 at 11 22 40 AM" …

Update badges on list search and recipe show heading

---

app/controllers/recipes_controller.rb
app/models/scraper.rb

This PR adds a super duper teeny tiny scraping helper to the "convert from experimental" workflow for recipes. Manually entering recipe ingredients and instructions isn't easy, but neither is scraping sites. This PR takes the first step in implementing some basic scraping to help make that process is a little bit easier. 
Essentially, it grabs all of the `<li>`s on a recipe site and dumps them in a big list in the `instructions` field of a new recipe. The user still has to manually enter the ingredients and delete all of the extraneous garbage that comes in as `<li>` content. This is a small step better than a direct copy/paste.
In the future, I may try to get the data more accurately. I may also want to implement a "new from url" workflow. I'll just use this for now to see how it goes.

Add wip ingredient scraper

---

app/controllers/shopping_lists_controller.rb
app/models/shopping_list.rb
app/models/shopping_list_item.rb
app/policies/shopping_list_policy.rb
app/views/shopping_lists/edit.html.erb
app/views/shopping_lists/index.html.erb
config/routes.rb
spec/models/shopping_list_item_spec.rb
spec/models/shopping_list_spec.rb
spec/policies/shopping_list_policy_spec.rb

* i mostly use the grocery list on this app
* i don't want to always make an extra click to get there with i sign in
* i moved some delete permission logic to the policy
* i added spec coverage for the new logic changes and also backfilled some spec coverage
* i made the grocery list items appear in alphabetical order by name under each aisle heading
The shopping_list show page requires a shopping list id, so now the shopping_list has a fallback of 
1 if it is in the params, return that list
2 if it is not in the params and the user has marked a "favorite list", return that list
3 if it is not in the params and the user has not chosen a "favorite list", return the default grocery list
* the pundit gem does has view helpers

Make grocery list home page

---

Gemfile
Gemfile.lock
app/models/aisle.rb
app/models/experimental_recipe.rb
app/models/ingredient.rb
app/models/inventory.rb
app/models/meal_plan.rb
app/models/meal_plan_recipe.rb
app/models/recipe.rb
app/models/scheduled_delivery.rb
app/models/shopping_list.rb
app/models/shopping_list_item.rb
app/models/user.rb
lib/tasks/auto_annotate_models.rake
spec/factories/aisles.rb
spec/factories/experimental_recipes.rb
spec/factories/ingredients.rb
spec/factories/inventories.rb
spec/factories/meal_plan_recipes.rb
spec/factories/meal_plans.rb
spec/factories/recipes.rb
spec/factories/scheduled_deliveries.rb
spec/factories/shopping_list_items.rb
spec/factories/shopping_lists.rb
spec/factories/users.rb

* the [`annotate` gem](https://github.com/ctran/annotate_models#configuration-in-rails) annotates chosen files (i chose models and factories) with the schema information for the associated table
* this makes it easier to know what fields you have available to you while working in models and specs
* it also lets you know what db defaults you have in place
* i like this
* this PR is a no-op. it only changes a `development` group gem and only adds comments to any app code files.

Add gem annotate

---

app/helpers/shopping_lists_helper.rb
app/models/shopping_list_item.rb

Closes #551
| Problem | Solution |
|---|---|
| "in cart" items showing up on more than one shopping list |"in cart" items now only show up on their parent shopping list. |
| "in cart" icon does not display if there is no associated upcoming delivery | if an item is marked as "in cart" even if there is no upcoming associated delivery, it now displays|
* Starting in Rails 6.1, scope syntax for `or` clauses no longer supported calling directly on the class. It has to be called on `self`. 
* https://stackoverflow.com/a/58650984

Fix cross-list bug and in_cart display

---

app/assets/javascripts/cable.js
app/controllers/shopping_list_item_statuses_controller.rb

Closes #793
* The `deactivate` controller action was not taking into account shopping list items that were `in_cart`. Since all items were `in_cart` an no items were `active`, the controller thought the aisle was empty.
* Scoping against `not_purcahsed` instead of `active` fixed the glitch

Bug fix: shopping list aisle being removed when items "in_cart"

---

.github/workflows/rubyonrails.yml
app/assets/stylesheets/icons.scss
app/components/material_icon.rb
app/controllers/experimental_recipes_controller.rb
app/controllers/recipes_controller.rb
app/helpers/shopping_lists_helper.rb
app/models/experimental_recipe.rb
app/models/scraper.rb
app/views/experimental_recipes/_form.html.erb
app/views/experimental_recipes/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/navbar/_main.html.erb
db/migrate/20231123123608_add_image_url_to_experimental_recipes.rb
db/schema.rb
spec/factories/experimental_recipes.rb

* adds an image to the experimental recipes page
* converts word links to icon links on the experimental recipes page
* adds accessibility improvements to application layout
* adds "filled" support to icon component
* replaces existing "star" icon with new filled-support version
* allows scraper to recover from when a recipe page blocks the copy attempt
* google material "icons" do not support filled/outlined modifications but their "symbols" do
* i was going to add automatic `aria-label`s to the icon class, but that label should go on the link, not the icon.

Add image to experimental recipes

---

config/initializers/sentry.rb

I was curious about performance, so I'm setting up sentry performance tracking: https://docs.sentry.io/platforms/ruby/guides/rails/performance/

Add sentry performance tracking

---

app/assets/stylesheets/recipes.scss
app/views/recipes/show.html.erb

* rearrange page elements to make more important things visible
* shrinks less-used stats into header
* i started messing around with my own styles instead of bootstrap, but will explore that in a separate PR
* allows us to see ingredients and instructions more easily 
| Before | After |
|------|--------|
| <img width="1428" alt="Screen Shot 2023-12-27 at 10 05 18 AM" src="https://github.com/lortza/food_planner/assets/8680712/17e9aa88-d3e3-417a-a99f-97abbef6a9c9"> | <img width="1424" alt="Screen Shot 2023-12-27 at 10 05 35 AM" src="https://github.com/lortza/food_planner/assets/8680712/e48c974e-7c52-4e7f-980f-52b90334221a"> |
| <img width="701" alt="Screen Shot 2023-12-27 at 10 05 07 AM" src="https://github.com/lortza/food_planner/assets/8680712/fc06f022-d146-4a02-9a58-a86e4d6975b9"> | …

Restyle recipe show

---

.github/workflows/rubyonrails.yml
.gitignore

I'm still trying to get the simplecov integration to work for dependabot PRs. I'm still not sure what's happening. I've tried:
* checking the repo workflow permissions
* adding (and then removing) SimpleCov to the branch protection rules
* following this blog post https://thewanderingcoder.com/2023/09/adding-github-actions-to-run-rspec-and-simplecov/
* investigating the `GITHUB_TOKEN` situation 
* https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
* https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
* this stackoverflow answer https://stackoverflow.com/a/70449620
* including the `coverage` directory, but gitignoring all files and folders in it

Add permissions to action

---

app/assets/stylesheets/shared.scss
app/assets/stylesheets/utilities.scss
app/views/shared/_delete_footer.html.erb

Closes #794
Makes the delete button harder to click on any given resource by moving it into a collapsed section.
* Adding `display: inline-block;` will let you use a header tag as part of the `<summary>` tag.

Collapse danger zone

---

README.md
app/controllers/meal_plans_controller.rb
app/views/meal_plans/_form.html.erb
app/views/meal_plans/edit.html.erb
app/views/meal_plans/new.html.erb
spec/rails_helper.rb
spec/requests/meal_plans_spec.rb

Closes [Sentry issue](https://anne-richardson.sentry.io/issues/5240185950/?referrer=alert_email&alert_type=email&alert_timestamp=1713825211748&alert_rule_id=1078349&notification_uuid=a1ab9cc7-a1f7-487f-81dd-fd23a696d7fb&environment=production)
* Fixes bug where meal_plan create has no error handling
* Fixes bug where meal_plan edit has no error handling
* somehow, i got away with not having values for the second instance variable in my `:create` and `:update` actions when the form could not submit properly
* oddly enough, i am sure i've bumped into errors on these forms before and never got the application bork message
* but the question remains: how did this ever work? neat. fun to encounter when trying to do food planning for the week.

Fix bug when create meal plan fails

---

app/views/devise/registrations/edit.html.erb
app/views/shared/navbar/_main.html.erb
app/views/shared/navbar/_signed_in.html.erb
config/routes.rb

* Allows a user to edit their password via web gui
* You can clobber out specific devise routes

Enable user edit of password

---

app/models/recipe.rb
app/views/recipes/_form.html.erb
app/views/recipes/show.html.erb
lib/tasks/recipe_tasks.rake
spec/factories/recipes.rb
spec/models/recipe_spec.rb

* prioritizes prep day content on recipe show page by swapping tab location
* prioritizes prep day content in recipe form by moving fields to make prep day & reheat first
* backfills prod data so prep day is not empty
* adds validations so prep day is not empty
* handles case where user forgets to fill in original recipe upon create

Prioritize prep day

---

Procfile

* removes overhead of needing to run `rake db:migrate` on the heroku server manually
* allows for this to be run automatically via instruction in the procfile

Auto run migrate on release

---

app/components/material_icon.rb
app/controllers/experimental_recipes_controller.rb
app/views/experimental_recipes/index.html.erb
config/initializers/date_formats.rb

I wanted a little more info on teh experimental recipes index. So i added the added-by date. To recoup some screen real estate, i changed the "convert" link to an icon. We'll see if I like it.

Add created-at date to experimental recipes index

---

app/views/meal_plans/new.html.erb
spec/requests/meal_plans_spec.rb

* the copy function for meal plans was not working because the `recipes` value was nil on the form.
* the simple fix to the `meal_plans/new` page was to actually provide that value correctly. 
* sentry: https://anne-richardson.sentry.io/issues/6837637156/?alert_rule_id=1078349&alert_timestamp=1756230679969&alert_type=email&environment=production&notification_uuid=be47e591-1613-4e87-8a39-539cc5166dde&project=5223691
This PR also comments out 2 flakey specs that have been problematic for a while.
* some previous work done a year ago broke this form

Bugfix: Populate recipes value for copied meal plans

---

app/components/material_icon.rb
app/controllers/recipes_controller.rb
app/helpers/recipes_helper.rb
app/models/recipe.rb
app/views/recipes/_form.html.erb
db/migrate/20251002174612_add_status_to_recipe.rb
db/migrate/20251002174907_backfill_recipe_status.rb
db/schema.rb
db/seed_fixtures/recipes.yml
spec/db/seeds_helper_spec.rb
spec/factories/recipes.rb
spec/helpers/recipes_helper_spec.rb
spec/models/recipe_spec.rb

* the `recipe` boolean `archived` will become obsolete when experimental recipes get rolled into regular recipes
* there is a new `status` enum that handles experimental recipes as `pending`, current regular recipes as `active` and archived recipes as `archived`
* this PR includes the migration for the new column as well as a backfill migration for the handful of currently archived recipes
* the checkbox on the recipe form is replaced with a status dropdown
* data migration to move experimental recipes to the recipes table
* schema migration to drop the `recipes.archived` bool

Create recipe status enum

---

app/components/material_icon.rb
app/helpers/recipes_helper.rb
app/views/recipes/_form.html.erb

* adds target blank link from recipe edit page to make it easier to see the source if a source is present
* make badge for "pending" recipes less bold
* change the badge for a "new" recipe to be easier to see

Add link to recipe source from edit page
